version: '2' # specify docker-compose version

services:
  client:
    build: client
    ports:
      - "4200:4200"

  server:
    build: server
    ports:
      - "3000:3000"
    links:
      - database

  database: 
    image: mongo
    ports:
      - "27017:27017"
